// Banco de preguntas — Instrumento de entrevista semiestructurada
// Diagnóstico organizacional MIO-Oil, C.A.
const DEPARTAMENTOS = {
  taller: {
    label: "Taller",
    preguntas: [
      "¿Cómo se recibe un cabezal o componente para reparación y qué información se registra al ingreso?",
      "¿Cómo se identifica cada equipo y sus piezas durante el desarme, diagnóstico y reparación?",
      "¿Cómo se determina qué componentes deben repararse, reemplazarse o descartarse?",
      "¿Cómo se apertura, actualiza y cierra una orden de trabajo de reparación?",
      "¿Qué planos, especificaciones o manuales se consultan durante una reparación y dónde se encuentran?",
      "¿Qué evidencias se generan durante la reparación y cómo se almacenan?",
      "¿Cómo se registran las inspecciones y pruebas realizadas antes de entregar un cabezal reparado?",
      "¿Cómo se relaciona una reparación con el cliente, el equipo intervenido y los repuestos utilizados?",
      "¿Cómo se solicita un repuesto al almacén y cómo se registra su consumo en una reparación?",
      "¿Cómo se controla el tiempo transcurrido entre la recepción y la entrega de un equipo reparado?",
      "¿Qué actividades generan mayores retrasos o reprocesos en el taller y con qué frecuencia ocurren?",
      "¿Cómo se identifica y corrige una reparación que no cumple con los requisitos técnicos establecidos?",
      "¿Cómo se registran las piezas defectuosas, daños encontrados o trabajos que deben repetirse?",
      "¿Cómo se controla el mantenimiento y disponibilidad de las máquinas y herramientas utilizadas en reparación?",
      "¿Cómo se verifica que el personal asignado tenga la competencia requerida para cada trabajo?",
      "¿Qué indicadores utiliza actualmente el taller para evaluar tiempos, productividad o calidad de las reparaciones?",
      "¿Cómo recibe el taller información de Ventas, Campo, Almacén o Contrataciones cuando esa información afecta un trabajo?",
      "¿Qué actividad del taller consume más tiempo por manejo manual de información?",
      "¿Qué información histórica de reparaciones sería útil analizar para anticipar fallas o mejorar diagnósticos?",
      "¿Qué funcionalidad debería tener un sistema digital para generar el mayor beneficio al taller desde el primer día?"
    ]
  },
  almacen: {
    label: "Inventario y Almacén",
    preguntas: [
      "¿Cómo se recibe un material o repuesto y qué información se registra al momento de ingresar al almacén?",
      "¿Cómo se identifica cada artículo para evitar confusiones entre piezas similares o de diferentes proveedores?",
      "¿Cómo se determina la ubicación de cada material y cómo se registra ese dato?",
      "¿Cómo se mantiene actualizado el saldo de inventario entre existencias físicas y registros digitales?",
      "¿Cómo se detectan y corrigen las diferencias entre inventario físico y registro?",
      "¿Cómo se controlan las condiciones de almacenamiento de materiales que requieren preservación especial?",
      "¿Cómo se registra y controla la recepción de piezas importadas hasta su disponibilidad para venta o servicio?",
      "¿Cómo se identifican y separan los materiales dañados, incorrectos o no conformes?",
      "¿Cómo se registra la salida de un material hacía Taller, Campo, Ventas u otro usuario?",
      "¿Cómo se puede conocer actualmente el historial de un repuesto desde su recepción hasta su consumo o entrega?",
      "¿Cómo se controla el préstamo, devolución y estado de las herramientas asignadas al personal técnico?",
      "¿Cómo se determina cuándo un material debe ser repuesto y quién recibe esa alerta?",
      "¿Cómo se conserva la información relacionada con lotes, proveedores y documentación de los materiales recibidos?",
      "¿Cómo se mide el tiempo desde que se solicita un material hasta que queda disponible para el usuario?",
      "¿Qué indicadores utiliza Almacén para evaluar exactitud, rotación, despachos o disponibilidad?",
      "¿Cómo se conecta la información de Almacén con Compras, Contrataciones, Finanzas, Taller y Ventas?",
      "¿Qué actividad del almacén genera más trabajo manual o riesgo de error?",
      "¿Qué análisis permitirían prever faltantes, exceso de inventario o necesidades futuras de repuestos?",
      "¿Qué utilidad tendría para el área incorporar códigos QR, barras u otra identificación digital?",
      "¿Qué funcionalidad debería implementar primero un sistema digital para mejorar la gestión del almacén?"
    ]
  },
  campo: {
    label: "Campo (Operaciones)",
    preguntas: [
      "¿Cómo recibe el equipo de Campo una solicitud de servicio y qué información necesita antes de movilizarse?",
      "¿Cómo se asigna el personal, herramientas y materiales para cada servicio en las instalaciones del cliente?",
      "¿Cómo se verifica que el personal y los recursos requeridos estén disponibles antes de salir a campo?",
      "¿Qué datos técnicos se registran durante un servicio y cómo se capturan?",
      "¿Qué evidencias de ejecución se generan en campo y cómo se entregan a la oficina o al cliente?",
      "¿Cómo se documenta un cambio en el alcance solicitado por el cliente durante un servicio?",
      "¿Cómo se comunica el personal de campo con la oficina cuando aparece una condición no prevista?",
      "¿Cómo se registra el tiempo de llegada, ejecución y cierre de cada servicio?",
      "¿Qué situaciones generan más retrasos o tiempo improductivo durante los servicios en campo?",
      "¿Cómo se verifica en campo que el trabajo realizado cumple los requisitos técnicos del cliente?",
      "¿Cómo se verifica antes y durante el servicio que se cumplen los controles HSE establecidos?",
      "¿Cómo se registra el equipo o componente intervenido y el trabajo realizado sobre él?",
      "¿Cómo se consulta el historial de servicios anteriores de un equipo o cliente?",
      "¿Cómo se elabora el informe final de servicio y cuánto tiempo toma prepararlo?",
      "¿Cómo se coordinan Campo, Taller, Almacén y Ventas cuando un servicio requiere piezas o reparaciones?",
      "¿Qué indicadores utiliza el área para evaluar cumplimiento de servicios, tiempos o satisfacción del cliente?",
      "¿Qué dificultades existen para capturar o consultar información cuando el personal está fuera de la oficina?",
      "¿Qué actividad administrativa del trabajo en campo sería la primera que automatizaría?",
      "¿Qué datos históricos de servicios podrían utilizarse para anticipar problemas o mejorar la planificación?",
      "¿Qué función debería resolver un sistema digital para mejorar de forma inmediata el trabajo del personal de Campo?"
    ]
  },
  calidad: {
    label: "Calidad",
    preguntas: [
      "¿Cómo se encuentran actualmente definidos y documentados los procesos que conforman el sistema de gestión de calidad?",
      "¿Cómo se asegura que el personal conozca los procedimientos e instrucciones que debe utilizar para ejecutar sus actividades?",
      "¿Cómo se controla actualmente la elaboración, revisión, aprobación y actualización de los documentos del sistema de gestión?",
      "¿Cómo se evita que el personal utilice versiones obsoletas de procedimientos, formatos o instrucciones?",
      "¿Dónde se almacenan actualmente los registros que sirven como evidencia del cumplimiento de los procesos?",
      "¿Cómo se garantiza que los registros de calidad puedan ser localizados posteriormente cuando se necesite reconstruir un servicio o proceso?",
      "¿Cómo se controla la trazabilidad de un equipo, pieza o servicio desde su recepción hasta su entrega al cliente?",
      "¿Cómo se gestionan actualmente los productos, materiales, equipos o servicios que no cumplen con los requisitos establecidos?",
      "¿Cómo se registran y analizan las no conformidades identificadas durante las operaciones o por los clientes?",
      "¿Cómo se determina y se realiza el seguimiento de las acciones correctivas derivadas de las no conformidades?",
      "¿Cómo se verifica que las acciones correctivas implementadas realmente solucionen la causa del problema?",
      "¿Cómo se gestionan actualmente las quejas, reclamos o devoluciones de los clientes?",
      "¿Cómo se evalúa el cumplimiento de los requisitos técnicos y de calidad establecidos por cada cliente antes de ejecutar un servicio o suministrar un producto?",
      "¿Cómo se preparan actualmente las evidencias y registros necesarios para atender una auditoría interna o externa?",
      "¿Cuáles son los aspectos del sistema de gestión que actualmente requieren mayor esfuerzo para demostrar cumplimiento durante una auditoría?",
      "¿Qué indicadores utiliza actualmente el departamento de Calidad para evaluar el desempeño y la eficacia del sistema de gestión?",
      "¿Cómo se identifican actualmente las oportunidades de mejora de los procesos y cómo se les realiza seguimiento?",
      "¿Qué actividades del sistema de gestión de calidad considera que generan mayor cantidad de trabajo administrativo o duplicación de registros?",
      "¿Qué funcionalidades debería tener un sistema digital para mejorar el control documental, la trazabilidad y el seguimiento de las acciones de calidad?",
      "¿En qué procesos de calidad considera que el análisis de datos o la inteligencia artificial podría aportar mayor valor para detectar desviaciones o apoyar la mejora continua?"
    ]
  },
  hse: {
    label: "HSE (Seguridad Industrial y Ambiente)",
    preguntas: [
      "¿Cómo se planifica la gestión HSE antes de ejecutar un trabajo en campo o taller?",
      "¿Cómo se identifican actualmente los peligros y se evalúan los riesgos asociados a cada actividad?",
      "¿Cómo se elaboran y aprueban actualmente los permisos de trabajo y los AST/JSA?",
      "¿Dónde se registra y almacena la información generada durante las actividades HSE?",
      "¿Cómo se verifica que los trabajadores asignados a una actividad tengan vigentes sus capacitaciones, certificaciones y competencias requeridas?",
      "¿Cómo se controla actualmente el estado y la disponibilidad del EPP requerido para las diferentes actividades?",
      "¿Cómo se realizan las inspecciones de seguridad y cómo se registran los hallazgos identificados?",
      "¿Cómo se reportan actualmente los incidentes, accidentes y condiciones inseguras?",
      "¿Cómo se gestionan los eventos que no generan un accidente, pero que podrían haberlo ocasionado?",
      "¿Cómo se realiza el seguimiento de las acciones correctivas derivadas de incidentes, inspecciones o reportes de seguridad?",
      "¿Qué información HSE considera más difícil de localizar cuando se necesita demostrar que un trabajo fue ejecutado de manera segura?",
      "¿Cómo se controla el cumplimiento de los requisitos HSE establecidos por los clientes antes y durante la ejecución de los servicios?",
      "¿Cómo se controla actualmente la condición de los vehículos, herramientas y equipos utilizados por el personal durante los servicios?",
      "¿Qué actividades HSE requieren actualmente mayor cantidad de registros manuales, transcripción o duplicación de información?",
      "¿Qué indicadores HSE se utilizan actualmente para evaluar el desempeño y cómo se consolidan?",
      "¿Cómo se comunican las alertas, cambios en los riesgos o desviaciones de seguridad al personal que se encuentra ejecutando los trabajos?",
      "¿Qué dificultades se presentan para obtener información HSE histórica de un trabajador, equipo, cliente o servicio específico?",
      "¿Qué proceso HSE considera que debería ser digitalizado prioritariamente para reducir tiempos y mejorar el control?",
      "¿En qué actividades HSE considera que una herramienta de análisis de datos o inteligencia artificial podría ayudar a anticipar riesgos o detectar patrones?",
      "¿Qué información o funcionalidades debería proporcionar un sistema digital para que el departamento HSE pudiera tomar decisiones de manera más rápida y confiable?"
    ]
  },
  finanzas: {
    label: "Finanzas",
    preguntas: [
      "¿Cómo se solicita, aprueba y da seguimiento a una requisición de materiales o repuestos?",
      "¿Cómo se elabora y controla el presupuesto de cada departamento?",
      "¿Qué reportes de gastos operacionales se generan y con qué periodicidad se revisan?",
      "¿Cómo se gestiona la facturación a clientes y el control de activos fijos (equipos, bombas)?",
      "¿Qué tan digitalizado está hoy el proceso financiero-administrativo (Excel, sistema, papel)?",
      "¿Qué información financiera sería más valiosa tener disponible en tiempo real para la toma de decisiones?",
      "¿Cuál es el proceso actual para la evaluación financiera y selección de proveedores críticos (requisito clave en auditorías de calidad)?",
      "¿Cómo manejan las cuentas por cobrar y qué alertas existen cuando un cliente entra en mora?",
      "¿Cómo se integran los datos de nómina y horas extras del personal de campo con el flujo de caja operativo general?",
      "Cuando hay una variación significativa entre el costo estimado de un proyecto y el costo real en campo, ¿cómo se documenta y se analiza?",
      "¿Qué controles o filtros existen actualmente para evitar pagos duplicados o errores en la cadena de suministros?",
      "¿Cómo miden la rentabilidad individual de los equipos de levantamiento artificial (BCP, Bombeo Mecánico) como activos fijos a lo largo de su vida útil?",
      "¿Qué porcentaje del tiempo del equipo de finanzas se invierte en transcripción manual de datos entre diferentes plataformas o libros de Excel?",
      "Al momento de una auditoría financiera o fiscal, ¿cuánto tiempo les toma recopilar todos los soportes documentales requeridos?",
      "¿Cómo gestionan la retención documental legal y contable? ¿Tienen un archivo físico centralizado, está descentralizado o está 100% digitalizado?",
      "¿Existe alguna matriz de riesgos financieros documentada y cómo se actualiza ante cambios en el entorno económico del país?",
      "¿Cómo se cruzan los datos de inventario real en el Taller con los registros contables para determinar el valor exacto del inventario inmovilizado?",
      "¿Cuáles son los principales cuellos de botella o reprocesos que retrasan los cierres contables mensuales?",
      "¿Cómo se manejan, aprueban y rinden los viáticos y anticipos de gastos para el personal técnico que viaja a las operaciones de campo?",
      "Si se implementa el nuevo Sistema de Gestión Digital, ¿qué módulo financiero consideran de prioridad \"crítica\" para automatizar desde el día uno?"
    ]
  },
  ventas: {
    label: "Aplicaciones y Ventas",
    preguntas: [
      "¿Cómo se registra y se da seguimiento a una oportunidad comercial desde el primer contacto con el cliente?",
      "¿Cómo se levantan y validan los requisitos técnicos y comerciales antes de preparar una oferta?",
      "¿Cómo se prepara, revisa y aprueba una cotización de servicios o productos?",
      "¿Cómo obtiene Ventas la información técnica necesaria de Taller o Campo para cotizar?",
      "¿Cómo se consideran los tiempos de importación y disponibilidad de piezas al comprometer una entrega al cliente?",
      "¿Cómo se controla el estado de una cotización desde su emisión hasta su aceptación o pérdida?",
      "¿Cómo se conserva el historial de comunicaciones, cotizaciones y servicios asociados a cada cliente?",
      "¿Cómo se transfiere una venta aprobada hacía Operaciones, Taller o Almacén?",
      "¿Cómo se documenta un cambio solicitado por el cliente después de aprobar una oferta?",
      "¿Cómo se gestionan las garantías, reclamos o devoluciones relacionadas con productos o servicios?",
      "¿Cómo se obtiene y registra la satisfacción del cliente después de un servicio o venta?",
      "¿Qué indicadores utiliza el área para medir conversión, ventas, tiempos o retención de clientes?",
      "¿Cómo se registran las oportunidades perdidas y qué información se conserva sobre sus causas?",
      "¿Cómo se comparte la información comercial con Finanzas, Contrataciones, Almacén y Taller?",
      "¿Cómo se controla que las fichas técnicas y documentos enviados al cliente sean los vigentes?",
      "¿Qué actividades comerciales generan más retrabajo por depender de correos, Excel o archivos dispersos?",
      "¿Cómo se prepara el pronóstico de ventas y qué información se utiliza para elaborarlo?",
      "¿Qué información comercial sería útil analizar automáticamente para priorizar oportunidades o anticipar necesidades del cliente?",
      "¿Qué información debería centralizar un CRM para que Ventas tenga una visión completa de cada cliente?",
      "¿Qué función debería tener el sistema digital para producir el mayor valor comercial desde el inicio?"
    ]
  },
  presidencia: {
    label: "Presidencia",
    preguntas: [
      "¿Cuáles son las prioridades estratégicas de la empresa para los próximos tres años?",
      "¿Qué indicadores utiliza la Dirección para evaluar el desempeño global de la organización?",
      "¿Cómo se consolida actualmente la información que utiliza la Presidencia para tomar decisiones?",
      "¿Qué información considera que debería estar disponible con mayor rapidez para decidir?",
      "¿Cuáles son los riesgos operacionales o comerciales que más preocupan actualmente a la Dirección?",
      "¿Qué problemas del modelo actual de gestión espera resolver mediante una transformación digital?",
      "¿Cómo evalúa la experiencia actual con Microsoft Power Platform utilizada por Contrataciones?",
      "¿Qué criterios serían indispensables para decidir entre ampliar Power Platform, adoptar otra solución o combinar herramientas?",
      "¿Cómo determina la Dirección la conveniencia económica de una inversión tecnológica?",
      "¿Qué resultados concretos deberían demostrarse para considerar exitosa una futura implementación digital?",
      "¿Qué importancia tiene para la Dirección fortalecer la gestión de calidad y la trazabilidad documental?",
      "¿Qué capacidades digitales considera necesarias para mejorar el servicio y la relación con los clientes?",
      "¿Qué crecimiento o nuevos servicios debería poder soportar el sistema en el futuro?",
      "¿Qué impacto considera que tendría la transformación digital sobre las capacidades y roles del personal?",
      "¿Qué factores podrían dificultar la adopción de un nuevo sistema dentro de la organización?",
      "¿Quién debería ser responsable de la gobernanza, priorización y seguimiento de la futura plataforma?",
      "¿Qué nivel de confianza tiene la Dirección en la calidad y disponibilidad de la información actual?",
      "¿Qué decisiones estratégicas podrían beneficiarse de alertas, análisis predictivos o asistentes basados en IA?",
      "¿Qué requisitos de seguridad y confidencialidad considera indispensables para la información corporativa?",
      "¿Qué factor sería decisivo para aprobar una futura solución digital: costo, eficiencia, control, servicio, cumplimiento o escalabilidad?"
    ]
  },
  contrataciones: {
    label: "Contrataciones",
    preguntas: [
      "¿Cómo se inicia y se gestiona actualmente una contratación desde la solicitud hasta su cierre?",
      "¿Cómo se reciben y validan los requerimientos técnicos, comerciales y documentales de una contratación?",
      "¿Cómo se registra y actualiza la información de proveedores y contratistas?",
      "¿Cómo se evalúan las propuestas de proveedores antes de seleccionar una alternativa?",
      "¿Cómo se distribuyen y controlan las aprobaciones dentro del proceso de contratación?",
      "¿Qué procesos de Contrataciones están actualmente soportados por Microsoft Power Platform?",
      "¿Qué información genera la plataforma y cómo se almacena o consulta posteriormente?",
      "¿Cómo se conecta actualmente Contrataciones con Finanzas, Almacén, Ventas u otras áreas?",
      "¿Cómo se controla la documentación requerida para cada contratación y su vigencia?",
      "¿Cómo se mide el tiempo desde la solicitud de contratación hasta la aprobación o adjudicación?",
      "¿Qué etapas del proceso generan más devoluciones, correcciones o reprocesos?",
      "¿Qué indicadores utiliza Contrataciones para evaluar tiempos, costos, cumplimiento o desempeño de proveedores?",
      "¿Cómo se puede reconstruir actualmente el historial completo de una contratación?",
      "¿Cómo se demuestra que una contratación siguió los controles y aprobaciones definidos?",
      "¿Qué limitaciones presenta actualmente Microsoft Power Platform para las necesidades del área?",
      "¿Qué procesos adicionales tendría sentido incorporar a la plataforma si la empresa decidiera ampliarla?",
      "¿Qué tareas de Contrataciones siguen siendo manuales y deberían automatizarse?",
      "¿Qué análisis o alertas automáticas serían útiles para evaluar proveedores, tiempos o riesgos de contratación?",
      "¿Qué información debería compartir Contrataciones con un sistema corporativo integrado?",
      "¿Qué mejora digital tendría mayor impacto en el proceso de contratación si se implementara primero?"
    ]
  }
};
